# Generated by Django 4.1.5 on 2023-02-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='h1',
        ),
    ]
