# Generated by Django 4.1.5 on 2023-02-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_remove_post_h1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
